name: service_providers
description: Package that handles the service providers logic.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 4.0.0
  equatable: 1.1.1
  list_diff: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
